const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.SpeechSynthesis,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Shape3D.Acts.RotateClockwise,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.AddInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Car.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{Car: 0},
	{Player: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{"3DShape": 0},
	{"3DCamera": 0},
	{HitCount: 0},
	{Bullet: 0},
	{Flash: 0},
	{PiggyBillboard: 0},
	{DestroyOutsideLayout: 0},
	{Tomato: 0},
	{Keyboard: 0},
	{Fade: 0},
	{PuffBillboard: 0},
	{Audio: 0},
	{TiledBackground2: 0},
	{btn_left: 0},
	{tecla: 0},
	{btn_right: 0},
	{btn_up: 0},
	{btn_tomate: 0},
	{Mouse: 0},
	{ControlTáctil: 0},
	{btn_down: 0},
	{Parpadeo: 0},
	{prueba_o_pregunta: 0},
	{SíntesisDeVoz: 0},
	{puntos_pregunta: 0},
	{puntosParaMarranito: 0},
	{disparar: 0},
	{tipo_pregunta: 0},
	{str_tipo_pregunta: 0},
	{str_secuencia_question_proof: 0},
	{puntos_x_question: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	PiggyBillboard: class extends self.I3DShapeInstance {},
	Tomato: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	PuffBillboard: class extends self.I3DShapeInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	btn_left: class extends self.ISpriteInstance {},
	btn_right: class extends self.ISpriteInstance {},
	btn_up: class extends self.ISpriteInstance {},
	btn_tomate: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ControlTáctil: class extends self.IInstance {},
	btn_down: class extends self.ISpriteInstance {},
	prueba_o_pregunta: class extends self.ITextInstance {},
	SíntesisDeVoz: class extends self.IInstance {},
	puntos_pregunta: class extends self.ITextInstance {}
}